jobs:
  include:
    - language: bash
      os: windows
      env: JAVA_HOME="C:\\Program Files\\OpenJDK\\openjdk-11.0.5_10"
    - language: java
      jdk: openjdk11
      os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then travis_retry choco install openjdk11 -y; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod +x gradlew; fi

script: ./gradlew check --scan

cache:
  directories:
    - $HOME/.gradle/
    - $HOME/.konan/

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: release
