jobs:
  include:
    - language: bash
      os: windows
    - language: java
      jdk: openjdk11
      os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then travis_retry choco install openjdk11 -y && ./refreshenv.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod +x gradlew; fi

script: ./gradlew check --scan

cache:
  directories:
    - $HOME/.gradle/
    - $HOME/.konan/

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: release
    tags: true
