jobs:
  include:
    - language: bash
      os: windows
      before_install:
        - chmod +x gradlew
    - language: java
      jdk: openjdk11
      os: osx
      before_install:
        - travis_retry choco install openjdk11 -y
        - refreshenv

script: ./gradlew check --scan

cache:
  directories:
    - $HOME/.gradle/
    - $HOME/.konan/

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: release